#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 11 00:28:02 2021

@author: suspect-0
"""

def minMax():
    intList = []
    while True:
        userInput = input("Please Enter an int: ")
        if userInput == 'done':
            # print out the largest and smallest num
            minNum = min(intList)
            maxNum = max(intList)
            print('Maximum is ', maxNum, '\nMinimum is ', minNum)
            break
        else:
            try:
                num = int(userInput)
                intList.append(num)
            except ValueError:
                print("Invalid input")
                
        
           
minMax()