#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  4 22:06:11 2021

@author: suspect-0
"""

# Assume s is a string of lower case characters.

# Write a program that prints the number of times the string 'bob' occurs in s. 
# For example, if s = 'azcbobobegghakl', then your program should print

# Number of times bob occurs is: 2


# let approache this by accessing the "o" letter

# s = 'azcbobobegghakl'
s = 'obboboobbobobkboobobbobobobobwbobobbobarbob'


countBob = 0
for i in range(len(s)):
    letter = s[i]
    if(letter == "o" and (0 < i < len(s) - 1)):
        left = s[i - 1]
        right = s[i + 1]
        if(left == "b" and right == "b"):
            countBob += 1

print("Number of times bob occurs is: ", countBob)
