#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 27 04:46:01 2021

@author: suspect-0
"""

def isPal(x):
    assert type(x) == list
    temp = x[:]
    temp.reverse()
    print(temp)
    if temp == x:
        return True
    else:
        return False


def silly():
    result = []
    elem = input('Enter element: ')
    for i in range(len(elem)):
        result.append(elem[i])

    print(result)
    if isPal(result):
        print('Yes')
    else:
        print('No')
        
        
print(silly())