#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  3 03:23:11 2021

@author: suspect-0
"""


# while True:
#     try:
#         n = input("Please enter an integer: ")
#         n = int(n)
#         break
#     except ValueError:
#         print("Input not an integer; try again")
        
# print("Correct input of an integer!")


def fancy_divide(list_of_numbers, index):
   denom = list_of_numbers[index]
   return [simple_divide(item, denom) for item in list_of_numbers]


def simple_divide(item, denom):
    try:
        return item / denom
    except ZeroDivisionError:
         return 0
        
        
print(fancy_divide([0, 2, 4], 0))
