#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  4 15:24:38 2021

@author: suspect-0
"""

for number in range(2, 11, 2):
    print(number)
    
print("Goodbye")


print("Hello!")

for number in range(10, 0, -2):
    print(number)