#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 15 14:46:55 2021

@author: suspect-0
"""

def is_prime(x):
    if x <= 1:
            return False
    for i in range(2, x // 2 + 1):
        if x % i == 0:
            return False
    return True


def genPrimes():
    num = 2
    while True:
        if is_prime(num):
            yield num
        num += 1
        
    

print(is_prime(26))


a = genPrimes()

for item in genPrimes():
    print(item)
    if item > 1000_000_000:
        break
    

    
    