#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 14 12:57:05 2021

@author: suspect-0
"""

def gcdIter(a, b):
    '''
    a, b: positive integers
    
    returns: a positive integer, the greatest common divisor of a & b.
    '''
    # Your code here
    testdiv = 0
    if a < b:
        testdiv = b
    else:
        testdiv = a
    
    for i in range(testdiv, 0, -1):
        if (a % i == 0) and (b % i == 0):
            testdiv = i
            break
    return testdiv    
        
        

print(gcdIter(9, 3))