#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 14 15:11:52 2021

@author: suspect-0
"""
def is_even(x):
    print("is_even ", x)
    if x == 0:
        return True
    else:
        return is_odd(x - 1)
    
    
def is_odd(x):
    print("is odd ", x)
    return not is_even(x)


print(is_odd(3))
print()
print(is_even(3))