#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 16 19:57:26 2021

@author: suspect-0
"""

def isIn(char, aStr):
    '''
    char: a single character
    aStr: an alphabetized string
    
    returns: True if char is in aStr; False otherwise
    '''
    # Your code here
    if aStr == "":
        return False
    right = len(aStr)
    left = 0
    middle = (right + left) // 2
    
    print(aStr[middle])

    if len(aStr) <= 1:
        return aStr[middle] == char
    elif aStr[middle] == char:
        return True
    else:
        if aStr[middle] < char:
            # right half
            return isIn(char, aStr[middle + 1:])
        else:
            #left half
            return isIn(char, aStr[:middle])
    


string = 'abcdefghiw'
print( isIn('n', 'cfffijkknnopqsstuuvw'))
# print(isIn('d', string))