#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  4 23:48:24 2021

@author: suspect-0
"""

# Assume s is a string of lower case characters.

# Write a program that prints the longest substring of s in which the letters occur in
# alphabetical order. For example, if s = 'azcbobobegghakl', then your program should 
# print

# Longest substring in alphabetical order is: beggh
# In the case of ties, print the first substring. For example, if s = 'abcbcd', 
# then your program should print

# Longest substring in alphabetical order is: abc

s = 'azcbobobegghakl'
s = 'ntbexglzokiiwxetcy'
s = 'ktmlvqojdnlcchs'


# This loop doesnot work!
# for i in range(len(s) - 1):
#     letter = s[i]
#     nextLetter = s[i + 1]
#     if(letter <= nextLetter):
#         currentStr += letter
#         print(currentStr)
#     else:
#         currentStr += letter
#         temp = currentStr
#         currentStr = ''
#         if(len(longestSubStr) < len(temp)):
#             longestSubStr = temp
    
# print(longestSubStr)

longestSubStr = ''
currentStr = ''
temp = ''











