#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 23 18:27:42 2021

@author: suspect-0
"""

def oddTuples(aTup):
    '''
    aTup: a tuple
    
    returns: tuple, every other element of aTup. 
    '''
    # Your Code Here
    
    return aTup[::2]        
        

tu = ('I', 'am', 'a', 'test', 'tuple')
print(oddTuples(tu))