#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 17 17:26:32 2021

@author: suspect-0
"""


balance = 4773
annualInterestRate = 0.2
monthlyInterestRate = annualInterestRate / 12.0
minimumMonthlyFixedPayment = 0
debtCovered = balance

while True:
    minimumMonthlyFixedPayment += 10
    month_balance = balance
    for i in range(12):  
        unpaidBalance = month_balance - minimumMonthlyFixedPayment
        month_balance += (monthlyInterestRate * unpaidBalance) 
    if month_balance * 12 >= balance:
        break
      

    
print(minimumMonthlyFixedPayment)
    
