#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 17 04:51:55 2021

@author: suspect-0
"""



balance = 5000
annualInterestRate = 0.18
monthlyPaymentRate = 0.02
 
balance = 42
annualInterestRate = 0.2
monthlyPaymentRate = 0.04
month = 1
while month < 13:
    print(month)
    monthlyPayment = monthlyPaymentRate * balance
    unpaidBalance = balance - monthlyPayment
    monthly_interest_rate = annualInterestRate * unpaidBalance / 12
    updatedBalance = unpaidBalance + monthly_interest_rate
    print(updatedBalance)
    balance = updatedBalance
    month += 1
    
    
print("Remaining balance ", round(balance, 2))