#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 14 01:59:46 2021

@author: suspect-0
"""

def recurPower(base, exp):
    '''
    base: int or float.
    exp: int >= 0
 
    returns: int or float, base^exp
    '''
    # Your code here
    
    if exp <= 0:
        return 1
    else:
        return base * recurPower(base, exp - 1)
    
    
print(recurPower(3, 3))