#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 11 09:54:06 2021

@author: suspect-0
"""

secret_num = 91
guess = 100 // 2
high = 100
low = 0
correct = False

print("Please think of a number between 0 and 100!")
while not correct :
    print("Is your secret number ", guess, "?")
    direction = input("Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. ")
    direction = direction.lower()
    if direction == 'l':
        # Too low
        print("you're in a l block")
        low = guess
        guess = (low + high) // 2
        
    elif direction == 'h':
        # Too high
        print("you're in a h block")
        high = guess
        guess = (low + high) // 2
        
    elif direction == 'c':
        correct = True
        print("Game over. Your secret number was: ", guess)
    else:
        print("Sorry, I did not understand your input.")
       